### ISSUE TITLE
Set of commands in `commands.py` should be limited to actual commands

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#13]
## Acceptance

* [x] `commands.py` contains only basic commands such as `summarize` and `check_score_accuracy` so it's easy to read.

## Tasks

* [x] Rename `check_score_accuracy_all_modules` to `check_score_accuracy` and update tests accordingly.
* [x] Move `check_score_accuracy_module` into `utils/commands_helpers.py`. Update code and tests as necessary.
