### ISSUE TITLE
Use Read the Docs to document the CLI

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#14]
## Acceptance

* [x] The project is set up with https://readthedocs.org/

## Tasks

1. reStructuredText:
    * Read:
      * [x] https://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/
      * [x] https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
    * Code:
      * [x] Convert existing Markdown to rST.
2. Sphinx:
    * Read: 
      * [x] https://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/
      * [x] https://www.sphinx-doc.org/en/master/
      * [x] https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html
    * Code:
      * [x] Install and configure.
3. Read the Docs:
    * Read:
      * [x] https://docs.readthedocs.io/en/stable/features.html
      * [x] https://docs.readthedocs.io/en/stable/config-file/v2.html
      * [x] https://docs.readthedocs.io/en/stable/webhooks.html
      * [x] https://docs.readthedocs.io/en/stable/intro/import-guide.html
    * Code:
      * [x] Configure and import.
      * [x] Add badges https://docs.readthedocs.io/en/stable/badges.html
4. Other sources:
    * Read:
      * [x] https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/

## Analysis

The README is starting to become cluttered. There will be more commands to be added and it's going to take a lot of space if an example output/result is to be given for each one.

**Comment by sglavoie** [comment]
FIXED: Done in bf08979e5201497e1d4b732862afacecdfd7b659.
