### ISSUE TITLE
Integrate Hypothesis to perform property-based testing

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#16]
## Acceptance

* [x] Hypothesis is used somewhere to uncover at least one bug.

## Tasks

* Explore the Hypothesis framework https://hypothesis.works/
  * Read:
    * [x] https://hypothesis.works/articles/writing-good-software/
    * [x] Some of https://hypothesis.works/articles/intro/
    * [x] Some of https://hypothesis.readthedocs.io/en/latest/
  * Watch:
    * [x] https://youtu.be/KcyGUVzL7HA from PyCon

## Analysis

Property-based testing allows one to try improbable combinations that may not have been thought of in order to break software in unexpected ways. It will result in interesting findings (at least for me) as there might be situations that are not currently being tested.

**Comment by sglavoie** [comment]
FIXED: Hypothesis is used in `mathtools` and showed that overflow errors weren't taken care of in 2a487dc2622bd6682c0f2bded6d8ee3d39309fa3. :slightly_smiling_face:
