### ISSUE TITLE
Should display a sensible message to the user when the output of the `summarize` command does not include data about any module

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#17]
## Acceptance

* [x] The tool displays a sensible message to the user when the output of the `summarize` command does not include data about any module.

## Tasks

* [x] Fix the outputs of the `summarize` commands (including for sub-commands `all`, `done` and `progress`) to display minimal info when no progress has been made in the degree.
  * [x] Do that for `progress`.
  * [x] Do that for `all`.
  * [x] Do that for `done`.

## Analysis

It's not a _"bug"_ per se, but it's annoying and possibly somewhat inaccurate too.

* If no modules at all have been taken, it's true that the student is failing in a way, but it's not helpful (true for the output of all sub-commands) :slightly_smiling_face:.
* If there are no modules in progress, the command `summarize progress` should helpfully say there's nothing in progress, not pretend the student is failing because there's no ongoing progress...
  * At some point, there won't be more progress to be made anyways, so the tool should also detect when the degree is 100% done.

Current useless output:

```
Modules in progress:
[]

Weighted average (including modules in progress): 0
 ECTS: E/F
 US: F

Unweighted average (including modules in progress): 0
 ECTS: E/F
 US: F

Classification (weighted): Fail

ECTS grade equivalence:
{}

US grade equivalence:
{}

GPA (weighted): 0 US – 0 UK
```
