### ISSUE TITLE
Should validate all values in the configuration file before allowing the user to use the tool in a cowboy manner

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#18]
## Acceptance

* [x] The tool validates fully the configuration file before proceeding.

## Tasks

* [x] Check line by line for syntax error (i.e. altered config file) to avoid checking all possible YAML issues.
* [x] Accept only values `4`, `5` and `6` for the level property.
* [x] Indicate type and value errors to the user instead of proceeding blindly (bad data is ignored, but still...).
* [x] Handle the case where the configuration file is empty a bit more gracefully.
* [x] Handle the cases where a module has no properties (e.g. just the line `Algorithms and Data Structures I:
`).
* [x] Handle syntax errors in the configuration file such that the user can understand what is going on.

## Analysis

Although the tool will work and perform appropriate calculations, having unexpected values in the configuration file could lead to unusual results.

* Syntax errors will certainly make the program complain right away, but the output of the error should be obvious.
* At this time, wrong data is simply discarded, but the user won't know about that (e.g. if the module score is 105, it won't be taken into account when calculating averages but the program won't say anything about it either in a "deal with it" manner).
* #17 should handle the case where properties are found but no actual useful data can be displayed.
