### ISSUE TITLE
Do not store module "level" value in JSON config file

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#2]
When I fill out information in the JSON configuration file, I want to focus on what needs user input and not have to care about other fixed values so that I don't make mistakes and do not have to work with cluttered configuration files when it's not necessary.

## Acceptance

* [x] `grades.json` and `grades-template.json` do not contain module information that's not absolutely necessary (i.e. remove the `level` property).

## Tasks

* [x] Refactor the code so that configuration values required by the program (not required directly by the user) are stored in an internal configuration file. JSON would still work well in this case.
* [x] Remove all references to the `level` property in `grades.json` and `grades-template.json`.
* [x] Update documentation in `README.md`.
* [x] Make sure that existing tests are refactored so that they test `level` values against a different fixture.

## Analysis

* Levels are known and defined in advance with a fixed set of modules. There's nothing to configure as such.

Only a score is needed right now to get stats back. So this:
```
"Algorithms and Data Structures I": {
    "score": -1,
    "level": 4
  }
```

Should really become this:
```
"Algorithms and Data Structures I": {
    "score": -1
  }
```

The skeleton should then contain only the name of the module and be composed of an empty object:
```
"Algorithms and Data Structures I": {}
```

To be more useful, it could just use a dummy value and the code would skip modules that don't contain a score represented as an integer or a float so it remains pre-filled for the user:
```
"Algorithms and Data Structures I": {
    "score": value
}
```

**Comment by sglavoie** [comment]
**FIXED**: Taken care of in 4968d0a9f0ba644e12439b9166e695e0b00dfee2.
