### ISSUE TITLE
Should test against out-of-bounds grades and TypeError

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#24]
## Acceptance

* [x] Code is tested for out-of-bound numeric errors.
* [x] Code raises TypeError if the value does not have a valid type in a module.

## Tasks

* [x] Test scores for failing module (< 35 or avg. < 40).
* [x] Test invalid numeric scores (> 100).
* [x] Raise error on TypeError and ValueError (< 0, > 100) on score.

## Analysis

So far, those errors were ignored, but it should raise an error instead and deal with edge cases better.
