### ISSUE TITLE
Output of `summarize` should display the results with nice tables instead of ugly JSON

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#26]
## Acceptance

* [x] The output of the `summarize` command and its sub-commands does not look too bad and uses tables instead.

## Tasks

* [x] Use `pandas` to generate tables and some script to pretty-print to the terminal (see https://stackoverflow.com/a/60202636/8787680).
* [x] Modify existing outputs to display table-like outputs instead of JSON-like outputs.

## Analysis

* I think displaying plain text in the terminal will be the most convenient option at this time. Fancy stuff later...
* `pandas` will be desirable to add options like sorting, filtering, aggregation, adding/removing columns, etc. So instead of using a simpler library like https://pypi.org/project/beautifultable/1.0.1/ (which has some minor issues for this particular use case with names in the header row, for instance, plus it doesn't provide pretty much any of the features that come with `pandas`), let's go straight with `pandas` as it will make it a lot easier to produce plots with `matplotlib` later as an added bonus.

**Comment by sglavoie** [comment]
Some testing with https://pypi.org/project/beautifultable/1.0.1/

![image](https://user-images.githubusercontent.com/32682903/122650200-2fa87200-d0f7-11eb-8545-e2c94dfd366b.png)

It works, but it's limited. Updated the description to use `pandas` instead.

**Comment by sglavoie** [comment]
FIXED: Using Pandas to display tables.

![image](https://user-images.githubusercontent.com/32682903/126877096-31839a0a-4ba0-4534-b699-eb8c976a8111.png)
![image](https://user-images.githubusercontent.com/32682903/126877108-a485c352-dc0e-492f-b29b-7e78c36edf2c.png)
