### ISSUE TITLE
Should have a feature to plot progress over time and save the results to PNG images

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#29]
## Acceptance

* [x] Users can generate images of plots showing the progress they have made in the degree.
* [x] All outputs are PNG images with good resolution and minimal padding around the exported figure.
* [x] Documentation is up-to-date about the new sub-command and its flags.

## Tasks

* [x] Ensure no plot is generated when there's not enough data.
* [x] Add command `plot`.
  * [x] Add a sub-command `modules`: This would be a scatter plot showing all individual grades over time.
    * [x] Add flag `--no-avgs` to remove all weighted and unweighted averages as lines.
    * [x] Add flag `--no-unweighted-avg` to plot the unweighted average as a line.
    * [x] Add flag `--no-weighted-avg` to remove the weighted average as a line.
    * [x] Add flag `--no-overall-avg` to remove the weighted average obtained across the degree.
    * [x] Add flag `--no-grades` to annotate points with the module name without showing the score next to it.
    * [x] Add flag `--no-module-names` to remove the display of module names entirely.
    * [x] Add flag `--no-trend` to remove the trend line.
    * [x] Add flag `--long-module-names` to display complete module names instead of their shortened version (i.e. _"Introduction to Programming I"_ instead of _"ITP1"_).
    * [x] Add flag `--dpi` to specify the output quality in dots per inch.
    * [x] Add flag `--no-date-in-title` to remove the bit that says _"as of YYYY-MM-DD"_.
    * [x] Add flag `--title` to allow changing the title of the graph (would not append any date in this case).
    * [x] Add flag `--keep-date-in-title` to append today's date to the title when used in conjunction with `--title`.
* [x] Add flag `--path` so users can choose where to save the output. If not specified, that would be the current working directory.
* [x] Add flag `--filename` to specify how the image output should be named (part without extension).
* [x] Display a message to the user saying where the output was saved, if any.
* [x] Map all long module names to their shorter equivalent (e.g. ITP1, ADS2...).
* [x] Check whether the output file already exists (same filename) and offer to overwrite it.
* [x] Add examples for this new command `ugc plot modules` to the documentation and document the command itself.
* [x] Bump version to `0.10.0`.

## Analysis

In this basic implementation, `pandas` dataframes would be used to create time series and `matplotlib` will take care of saving the output. Simple table to plot conversion to start with.

**Comment by sglavoie** [comment]
FIXED: All tasks were done.
