### ISSUE TITLE
Any negative value passed to `get_percentage_degree_done` should return -1

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#32]
#### Issue description

`get_percentage_degree_done` returns negative results when the input is negative.

#### Steps to reproduce the issue

```
>>> from ugc.grades import Grades
>>> Grades().get_percentage_degree_done(150)
41.67
>>> Grades().get_percentage_degree_done(315)
87.5
>>> Grades().get_percentage_degree_done(360)
100.0
>>> Grades().get_percentage_degree_done(3600)
-1
>>> Grades().get_percentage_degree_done(0)
0.0
>>> Grades().get_percentage_degree_done(-0)
0.0
>>> # errors from that point on
>>> Grades().get_percentage_degree_done(-1)
-0.28
>>> Grades().get_percentage_degree_done(-100)
-27.78
>>> Grades().get_percentage_degree_done(-0.1)
-0.03
```

#### What's the expected result?

`-1` for all negative values.

#### What's the actual result?

Negative floating values that can be different to `-1`.

---

## Tasks

* [x] Test `get_percentage_degree_done` properly with pytest.
* [x] Implement the needed change in the source code.
* [x] Bump patch version.

## Analysis

This is an error that won't be encountered in normal use since the CLI will not pass a negative value to `get_percentage_degree_done`. It's only doable by calling the function directly.
