### ISSUE TITLE
Use JSON format for the config file instead of YAML

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#33]
## Acceptance

* [x] `ugc` uses the JSON format exclusively for its config file and for any output produced.

## Tasks

* [x] Update default path from `.grades.yml` to `.ugc-grades.json`.
* [x] Update fixtures in `tests/conftest.py`.
* [x] Update tests and function names in `tests/test_config.py`.
  * [x] Change the `__init__` and `load` methods of the `Config` class to read from JSON.
  * [x] Change how `check_config_format_is_syntactically_correct` operates.
* [x] Update the examples in `docs/introduction.rst` to use JSON instead of YAML.
* [x] Remove Asciinema demo.
* [x] Bump minor version.

## Analysis

YAML led to an interesting ride, but it's just way more convenient to work with JSON files in https://github.com/sglavoie/uol-grades-calculator-server so to avoid constant conversions from one format to the other, YAML should be ditched in favor of JSON.
