### ISSUE TITLE
Should allow loading grades from a JSON string

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#34]
## Acceptance

* [x] `ugc` can load grades data from a JSON string passed via the `--json` option (in the same way that the path to the config file can be changed with `--config`).

## Tasks

* [x] Add tests against new `--json` option with Hypothesis.
* [x] Add `--json` option to `def cli(ctx, config)` in `cli.py`.
  * [x] First load from JSON data if the `--json` option is passed, otherwise load from `--config`, otherwise try to load from the default config path. `--json` will take precedence if both `--json` and `--config` are passed as the idea is to use ephemeral data instead of data stored on disk for an API to work.
* [x] In the `__init__` method of `Grades`, load data from the JSON instead of from the file if the `json` parameter has a value. Perform the same checks as before to validate the data.
* [x] In the `load` method of `Config`, set `self.data` to the JSON received instead of reading from a file.

## Analysis

* Needed by https://github.com/sglavoie/uol-grades-calculator-server/issues/4.
* The current behavior is to load grades from a local configuration file.
* However, to set things up with a server calling `ugc`, we don't want to load from a file but receive the data via a string instead. Something like:

```bash
ugc --json '{ "Algorithms and Data Structures I": { "completion_date": "2020-03", ...'
```

To do this, `cli.py` should receive the JSON string before instantiating `Grades` in `def cli(ctx, config)` and it should accept a `json` argument to pass the string to the function. In the `__init__` method of `Grades`, the JSON would be validated and `self.data` would use the incoming JSON string and get a dictionary from it instead of loading from a file. This way, all calls made by the back-end would instantiate a new `Grades` object so that any changes made in the JSON data in the UI could be sent to the back-end with up-to-date data that will be loaded on the fly before using any `ugc` command from the CLI.
