### ISSUE TITLE
Should make use of `pre-commit` hooks to enforce good coding standards

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#36]
* https://pre-commit.com/

## Acceptance

* [x] `ugc` makes use of `pre-commit` locally (e.g. via `.pre-commit-config.yaml`). — See 29d86a4f050c162f8a366146990acda8bdce101b
* [x] `pre-commit` runs on each pull request. — See successful check with #37 
* ~`ugc` makes use of a GitHub Actions workflow to enforce standards on pull requests (I can keep creating them :slightly_smiling_face:).~

## Tasks

* [x] Investigate how to use `pre-commit` at https://pre-commit.com/.
* [x] Figure out which hooks might be interesting/useful to use and install them https://github.com/pre-commit/pre-commit-hooks.
* [x] Check what `.pre-commit-hooks.yaml` is for and use it if necessary (see https://github.com/pre-commit/pre-commit-hooks).
* [x] Add the necessary configuration files to the project.
* ~Create a GitHub Actions workflow that will be triggered on pull requests on the `main` branch.~ Not required: there is pre-commit.ci

**Comment by sglavoie** [comment]
FIXED: All tasks were done.
