### ISSUE TITLE
Command `generate-sample` fails to work if `.ugc-grades.json` already exists and is invalid

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#39]
## Acceptance

* [x] `ugc generate-sample -f` removes the configuration file without validating it and forcefully generates a new sample.
* [x] `ugc generate-sample` warns if `.ugc-grades.json` already exists and raises a `ugc.config.ConfigValidationError` if there's one.

## Tasks

* [x] Fix the mess.
