### ISSUE TITLE
Calculator should have new attributes to keep track of midterm/final scores independently

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#4]
When I store results with this calculator, I want to be able to keep track of midterm and final results separately from the module "average" so I can analyze more precise data points.

## Acceptance

* [x] In `grades.yml`, the attribute `score` becomes `module_score`.
* [x] In `grades.yml`, there are new attributes for each module to keep track of scores as follows:
  * [x] `final_score` and `final_weight` keep track of the final score (final submission, i.e. exam or final project in a given module).
  * [x] `midterm_score` and `midterm_weight` keep track of the midterm score (whatever the type of submission that is).

## Tasks

* [x] Rename attribute `score` to `module_score` to clearly define the scope of the result (i.e. weighted average of everything in the module).
* [x] Add new attributes as defined in the **Acceptance** criteria in `grades.yml` and `src/grades-template.yml` for convenience.
* [x] Update tests and source code to use new attribute `module_score` instead of `score`.
* **FUTURE**: Implement calculations for midterms, finals and weighted module average (new issue).

## Analysis

* The attribute `module_score` can be kept for reference as that's the final score given by the University. The calculator could then use that score and compare with the weighted average of the different submissions (midterm + final) in the module to make sure no error was made in the final grade for the module.
