### ISSUE TITLE
Should have a function to check for errors when calculating the module average (final grade of a given module)

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#7]
* Dependency: #6 

When I input my score for the mid-term and final coursework for a module, I want to be able to confirm there are no errors (even if it's just a rounding error) by comparing the value the calculator gets with the official result shared by UoL.

## Acceptance

* [x] The tool calculates the expected `module_score` and outputs the results for all modules that have any mismatch.
* [x] This functionality is being tested and considers edge cases (rounding up/down, `TypeError`, etc.).

## Tasks

* [x] Create a command `check` which will contain sub-commands.
* [x] Create sub-command `score-accuracy` for the command `check`.
* [x] Write test for the logic which will be contained in the sub-command.
* [x] Write code that makes the test pass.

## Analysis

A sample module looks like this (slightly stripped down to keep the relevant portion):

```yaml
Algorithms and Data Structures I:
  final_score: 92
  final_weight: 50
  midterm_score: 98
  midterm_weight: 50
  module_score: 95
```

To check whether `module_score` has the expected value (which was determined by UoL), we do the following calculation:

```
midterm_score * midterm_weight / 100 + final_score * final_weight / 100
```

The calculator should store in a list all modules where the calculated values do not match (i.e. `module_score != expected_score`). The presentation is up to the implementer :wink:...
