### ISSUE TITLE
Have a command to generate a sample `grades.yml`

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/uol-grades-calculator#9]
## Acceptance

* [x] A user can run `python -m uol_grades_calculator generate-sample` (or `ugc generate-sample`) to get a sample `grades.yml` file pre-filled with relevant information in the expected location (note: location and filename depends on the resolution of #8).

## Tasks

* [x] Test against overwriting existing `.grades.yml`. Just warn in this case, don't do anything.
* [x] Write `generate_sample` function that copies over the `grades-template.yml` file to `~/.grades.yml` in a cross-platform way.
* [x] Add `-f`/`--force-overwrite` option to allow the user to overwrite the content of the existing config file, if any.

## Analysis

The current step describing how to copy a `grades-template.yml` in https://github.com/sglavoie/uol-grades-calculator/blob/aa77b8dbf162c78088f50b45f39132492e5a0aa2/README.md#complete-sample-yaml-file is not useful once this tool is made available as a Python package. So it will make it easier for the user to just have a command that generates a sample on the fly in the correct location.
